spring:
  profiles: default
  main:
    banner-mode: "off"
    #allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
    database: h2

  jackson:
    date-format: com.sawert.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
    # url: jdbc:h2:~/data/test
    url: jdbc:h2:tcp://localhost:9092/~/data/test
    username: sa
    password: 

  # datasource:
  #   driverClassName: com.mysql.cj.jdbc.Driver
  #   dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #   url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
  #   username: bsawert
  #   password: nopass

server:
  servlet:
    context-path: /doghouse
  port: 8080

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type: TRACE
    org.springframework.boot: WARN
    org.springframework.orm.jpa: DEBUG

h2:
  tcp:
    port: 9092
    enabled: true
  web:
    port: 8082
    enabled: true

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - info
          - health
          - beans
          - configprops
  endpoint:
    info:
      enabled: true

test:
  config:
    colors: Fawn, Black, Brindle

debug: true